---
# Php modules
php_modules: [ 'php-curl', 'php-gd', 'php-mbstring', 'php-xml', 'php-xmlrpc', 'php-soap', 'php-intl', 'php-zip' ]

# Mariadb settings
mysql_root_password: "your_mysql_password"
mysql_db: "your_db_name"
mysql_user: "your_user"
mysql_password: "your_user_password"

# HTTP Settings
http_host: "your_domain"
http_conf: "your_domain.conf"
http_port: "80"
